import React from 'react';
import { Info, Sparkles, CheckCircle, ArrowRight, MapPin } from 'lucide-react';
import { SlotRecommendation } from '@/lib/civic-intelligence';
import { cn } from '@/lib/utils';

interface AIExplanationPanelProps {
  recommendation: SlotRecommendation;
  onAccept?: () => void;
  onViewAlternates?: () => void;
}

export const AIExplanationPanel: React.FC<AIExplanationPanelProps> = ({
  recommendation,
  onAccept,
  onViewAlternates,
}) => {
  return (
    <div className="glass-card-elevated overflow-hidden animate-smooth-fade-in">
      {/* AI Disclosure Header */}
      <div className="px-6 py-4 bg-gradient-to-r from-primary/10 to-cyan-500/10 border-b border-border/30">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-primary/20 flex items-center justify-center">
              <Sparkles className="w-4 h-4 text-primary" />
            </div>
            <div>
              <span className="text-sm font-medium">AI Slot Recommendation</span>
              <p className="text-xs text-muted-foreground">
                Confidence: {Math.round(recommendation.factors.reduce((a, f) => a + f.weight, 0) * 100)}%
              </p>
            </div>
          </div>
          <div className="ai-disclosure">
            <Info className="w-3 h-3" />
            AI Assisted
          </div>
        </div>
      </div>

      {/* Main recommendation */}
      <div className="p-6 space-y-6">
        {/* Slot display */}
        <div className="text-center">
          <div className="inline-flex items-center gap-3 px-6 py-4 glass-subtle rounded-2xl glow-calm">
            <MapPin className="w-6 h-6 text-primary" />
            <div className="text-left">
              <div className="text-3xl font-display font-bold gradient-text">
                {recommendation.floor}-{recommendation.zone}-{recommendation.number}
              </div>
              <div className="text-sm text-muted-foreground">
                Level {recommendation.floor} • Zone {recommendation.zone}
              </div>
            </div>
          </div>
        </div>

        {/* Explanation - human-readable */}
        <div className="glass-subtle p-4 rounded-xl">
          <h4 className="text-sm font-medium mb-2 flex items-center gap-2">
            <Info className="w-4 h-4 text-primary" />
            Why this slot?
          </h4>
          <p className="text-sm text-foreground/80 leading-relaxed">
            {recommendation.explanation}
          </p>
        </div>

        {/* Factors breakdown */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium text-muted-foreground">Decision Factors</h4>
          {recommendation.factors.map((factor, index) => (
            <div 
              key={index}
              className="flex items-center gap-3 p-3 bg-muted/20 rounded-lg"
            >
              <div className="w-2 h-2 rounded-full bg-primary" />
              <span className="text-sm flex-1">{factor.factor}</span>
              <span className="text-xs text-muted-foreground">
                {Math.round(factor.weight * 100)}% weight
              </span>
            </div>
          ))}
        </div>

        {/* Alternate options */}
        {recommendation.alternateOptions.length > 0 && (
          <div>
            <h4 className="text-sm font-medium text-muted-foreground mb-2">
              Other Options
            </h4>
            <div className="flex gap-2">
              {recommendation.alternateOptions.map((alt, index) => (
                <button
                  key={index}
                  onClick={onViewAlternates}
                  className="glass-subtle px-3 py-2 rounded-lg hover:bg-muted/50 transition-all text-left flex-1"
                >
                  <div className="text-sm font-medium">{alt.slotId}</div>
                  <div className="text-xs text-muted-foreground">{alt.reason}</div>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Accept button */}
        {onAccept && (
          <button
            onClick={onAccept}
            className="w-full py-4 rounded-xl bg-gradient-to-r from-primary to-cyan-500 text-primary-foreground font-medium flex items-center justify-center gap-2 hover:opacity-90 transition-all shadow-lg glow-calm"
          >
            <CheckCircle className="w-5 h-5" />
            Accept Recommendation
            <ArrowRight className="w-5 h-5" />
          </button>
        )}
      </div>

      {/* Transparency footer */}
      <div className="px-6 py-3 bg-muted/20 border-t border-border/30">
        <p className="text-xs text-muted-foreground text-center">
          This recommendation is generated by AI to assist you. You may choose any available slot.
        </p>
      </div>
    </div>
  );
};
